name: Generate SVM Assets
inputs:
  verify_version:
    description: "Solana verify version to install (leave empty to skip)"
    required: false
    default: ""
  node_version:
    description: "Node version to install"
    required: true
  cargo_toolchain:
    description: "Cargo toolchain to install"
    required: false
    default: "stable"
  cargo_components:
    description: "Cargo components to install"
    required: false
    default: "rustc"
runs:
  using: "composite"
  steps:
    - name: Extract Solana versions
      uses: solana-developers/github-actions/extract-versions@v0.2.5
      id: versions
    - name: Setup Anchor & Solana
      uses: solana-developers/github-actions/setup-all@v0.2.5
      with:
        anchor_version: ${{ steps.versions.outputs.anchor_version }}
        solana_version: ${{ steps.versions.outputs.solana_version }}
        verify_version: ${{ inputs.verify_version }}
        node_version: ${{ inputs.node_version }}
    - name: Install Cargo toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.cargo_toolchain }}
        profile: minimal
        components: ${{ inputs.cargo_components }}
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
