name: Cache SVM Assets
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.svm-assets-cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Cache SVM assets
      id: svm-assets-cache
      uses: actions/cache@v4
      with:
        path: |
          target/idl
          target/types
          src/svm/assets
          src/svm/clients
        key: v0-debug-svm-assets-${{ runner.os }}-${{ hashFiles('Cargo.lock', 'programs/**/Cargo.toml', 'programs/**/Xargo.toml', 'programs/**/*.rs') }}
