# Reusable action to cache SVM assets if the source code has not changed.
name: Cache SVM Assets
inputs:
  name:
    description: "Name of the assets, used in cache key"
    required: true
  path:
    description: "Cache path to use"
    required: true
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.svm-assets-cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Cache SVM assets
      id: svm-assets-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: svm-assets-${{ inputs.name }}-${{ runner.os }}-${{ hashFiles('Cargo.lock', 'programs/**/Cargo.toml', 'programs/**/Xargo.toml', 'programs/**/*.rs') }}
