name: Cache SVM Assets
runs:
  using: "composite"
  steps:
    - name: Cache SVM assets
      id: svm-assets-cache
      uses: actions/cache@v4
      with:
        path: |
          target/idl
          target/types
          src/svm/assets
          src/svm/clients
        key: v0-svm-assets-${{ runner.os }}-${{ hashFiles('Cargo.lock', 'programs/**/Cargo.toml', 'programs/**/Xargo.toml', 'programs/**/*.rs') }}
    - name: Export cache hit status
      run: echo "cache-hit=${{ steps.svm-assets-cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
