name: Checks
on: [push, pull_request]
jobs:
  # Multiple jobs depend on having SVM artifacts available, so we upload them first in a separate job.
  upload-svm-idl-artifacts:
    name: Upload SVM IDL artifacts
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_PATHS: |
        target/idl
        target/types
        src/svm/assets
        src/svm/clients
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache SVM IDL artifacts
        id: svm-idl-artifacts-cache
        uses: ./.github/actions/cache-svm-assets
        with:
          name: idl-artifacts
          path: ${{ env.ARTIFACTS_PATHS }}
      - name: Generate SVM IDL artifacts
        if: steps.svm-idl-artifacts-cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/generate-svm-idl-artifacts
        with:
          node_version: ${{ matrix.node }}
      - name: Upload SVM IDL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: svm-idl-artifacts-node-${{ matrix.node }}
          path: ${{ env.ARTIFACTS_PATHS }}
          if-no-files-found: error
  upload-evm-artifacts:
    name: Upload EVM artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Build EVM
        run: yarn build-evm
      - name: Upload EVM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: evm-artifacts-node-${{ matrix.node }}
          path: |
            artifacts
            cache
            typechain
          if-no-files-found: error
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Install Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustc, rustfmt
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint js
        shell: bash
        run: yarn lint-js
      - name: Lint solidity
        shell: bash
        run: yarn lint-solidity
      - name: Lint rust
        shell: bash
        run: yarn lint-rust
  test-evm:
    name: Test EVM
    # Mixed leaf tests also require SVM types from assets that have been uploaded in the artifacts.
    needs:
      - upload-svm-idl-artifacts
      - upload-evm-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Download SVM IDL artifacts
        uses: actions/download-artifact@v4
        with:
          name: svm-idl-artifacts-node-${{ matrix.node }}
      - name: Download EVM artifacts
        uses: actions/download-artifact@v4
        with:
          name: evm-artifacts-node-${{ matrix.node }}
      - name: Test evm-hardhat
        shell: bash
        run: yarn test-evm
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Extract Solana versions
        uses: solana-developers/github-actions/extract-versions@v0.2.5
        id: versions
      - name: Setup Anchor & Solana
        uses: solana-developers/github-actions/setup-all@v0.2.5
        with:
          anchor_version: ${{ steps.versions.outputs.anchor_version }}
          solana_version: ${{ steps.versions.outputs.solana_version }}
          node_version: ${{ matrix.node }}
      - name: Install Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test evm-hardhat
        shell: bash
        run: yarn test-evm
      - name: Test svm-anchor
        shell: bash
        run: yarn test-svm
  test-svm-verified:
    name: Test verified SVM build
    needs: upload-svm-idl-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Setup Anchor & Solana
        uses: ./.github/actions/setup-solana-anchor
        with:
          verify_version: 0.4.3
          node_version: ${{ matrix.node }}
      - name: Download SVM IDL artifacts
        uses: actions/download-artifact@v4
        with:
          name: svm-idl-artifacts-node-${{ matrix.node }}
      # Cargo cache would only apply to dependencies that are not reused in the verified docker build, hence we need to
      # manually cache the verified build binaries if the program source code has not changed.
      - name: Cache verified test build binaries
        id: verified-test-build-cache
        uses: ./.github/actions/cache-svm-assets
        with:
          name: verified-test-binaries
          path: target/deploy
      - name: Create verified build
        if: steps.verified-test-build-cache.outputs.cache-hit != 'true'
        env:
          IS_TEST: true
        run: yarn build-svm-solana-verify
      - name: Test verified SVM build
        run: anchor test --skip-build
  build-svm-verified:
    name: SVM verified production build
    needs: upload-svm-idl-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Setup Anchor & Solana
        uses: ./.github/actions/setup-solana-anchor
        with:
          verify_version: 0.4.3
          node_version: ${{ matrix.node }}
      - name: Download SVM IDL artifacts
        uses: actions/download-artifact@v4
        with:
          name: svm-idl-artifacts-node-${{ matrix.node }}
      # Cargo cache would only apply to dependencies that are not reused in the verified docker build, hence we need to
      # manually cache the verified build binaries if the program source code has not changed.
      - name: Cache verified production build binaries
        id: verified-production-build-cache
        uses: ./.github/actions/cache-svm-assets
        with:
          name: verified-production-binaries
          path: target/deploy
      - name: Create verified build
        if: steps.verified-production-build-cache.outputs.cache-hit != 'true'
        run: yarn build-svm-solana-verify
      # - name: Test verified SVM build
      #   run: anchor test --skip-build
  build-ts:
    name: Build TypeScript
    needs:
      - upload-svm-idl-artifacts
      - upload-evm-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Download SVM IDL artifacts
        uses: actions/download-artifact@v4
        with:
          name: svm-idl-artifacts-node-${{ matrix.node }}
      - name: Download EVM artifacts
        uses: actions/download-artifact@v4
        with:
          name: evm-artifacts-node-${{ matrix.node }}
      - name: Build TypeScript
        run: yarn build-ts
  forge:
    name: Forge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Install packages
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install forge dependencies
        run: forge install
      - name: Inspect storage layouts
        run: ./scripts/checkStorageLayout.sh
      - name: Test evm-foundry
        run: forge test --match-path test/evm/foundry/local/**/*.t.sol
